#!/usr/bin/env bash
#
# Summary: Set NODENV_VERSION for the lifetime of a shell.
#
# Usage: nodenv shell <version>
#        nodenv shell --unset|-u

# Bomb out if we hit an error, ever
set -e

# Verbose output in debug mode
[ -n "$NODENV_DEBUG" ] && {
  set -x
}

version_installed() {
  local v="$1"
  [ -d "${NODENV_ROOT}/versions/${v}" ]
}

# Set the version
version="$1"

case "$version" in
  "")
    if [ -z "$NODENV_VERSION" ]; then
      echo "nodenv: no shell version configured" >&2
      exit 1
    else
      echo "echo \"$NODENV_VERSION\""
    fi
    ;;

  "-u" | "--unset")
    echo "unset NODENV_VERSION"
    ;;

  *)
    export NODENV_VERSION="$version"

    if version_installed "$version"; then
      echo "export NODENV_VERSION=\"${version}\""
    else
      echo "nodenv: version \`${version}' is not installed" >&2
      exit 1
    fi
    ;;
esac
