#!/usr/bin/env bash
# Summary: Install a version of NodeJS.
#
# Usage: nodenv install <version> [--source]
#
# Versions should be in the form of vN.N.N
#
# If --source is given, tries to build NodeJS from source.

# Bomb out if we hit an error, ever
set -e

# Verbose output in debug mode
[ -n "$NODENV_DEBUG" ] && {
  set -x
}

list_definitions() {
  { curl -s "http://nodejs.org/dist/" | \
    awk 'match($0,/>(v[0-9]+\.[0-9]+\.[0-9]+)\/</) { print substr($0, RSTART + 1, RLENGTH - 3); }' -
  } | sort_versions | uniq
}

sort_versions() {
  LC_ALL=C sort -t. -k 1,1 -k 2,2n -k 3,3n -k 4,4n -k 5,5n
}

verified_download() {
  url="$1"
  filename=$(basename "$url")
  shasum_url=$(dirname "$url")/SHASUMS256.txt
  download_dir=$(mktemp -d /tmp/nodenv.XXXXXX)
  curl --silent --show-error --fail "$url" --output "$download_dir/$filename" || return 1
  if curl --silent --show-error --fail "$shasum_url" --output "$download_dir/SHASUMS256.txt"; then
    # make a checksum file with only one entry
    awk -v "f=$filename" '$2 == f' "$download_dir/SHASUMS256.txt" > "$download_dir/SHASUM.txt"
    (
      cd "$download_dir"
      shasum -a 256 -c "SHASUM.txt" >/dev/null
    ) || {
      rm -rf "$download_dir"
      echo "ERROR: Download of $url failed checksum check" >&2
      return 1
    }
  else
    echo "WARNING: $shasum_url not found, download cannot be verified." >&2
  fi
  # Provide downloaded, verified filename to caller
  echo "$download_dir/$filename"
}

# Provide nodenv completions
if [ "$1" = "--complete" ]; then
  list_definitions
  exit 0
fi

# Sugar for install latest version of iojs
if [[ $1 == iojs ]]; then
  iolatest=$(curl -s -f https://iojs.org/dist/index.tab | head -n 2 | awk 'NR==2{print $1}')
  set -- "iojs-$iolatest" "${@:2}"
fi

# Pull the desired version out of ARGV
version="$1"
version_dir="$NODENV_ROOT/versions/$version"

# stash the pwd
OLDPWD=$(pwd)

# Are we going to compile this instead?
compile="$2"

# Make the version dir and get in there
mkdir -p "$version_dir"
cd "$version_dir"

if [ "$compile" = "--source" ]; then
  # Let's fetch the source and build it
  if [[ $1 == iojs-* ]]; then
    ioversion=${1##*-}
    work_dir="/tmp/iojs-$ioversion"
    download="https://iojs.org/dist/${ioversion}/iojs-${ioversion}.tar.gz"
    # There is no tarballs at alternatives places on io.js project, so try again!
    alt_download="https://iojs.org/dist/${ioversion}/iojs-${ioversion}.tar.gz"
  else
    download="https://nodejs.org/dist/${version}/node-${version}.tar.gz"
    alt_download="https://nodejs.org/dist/node-${version}.tar.gz"
    work_dir="/tmp/node-$version"
  fi

  # Can't get too clever here
  set +e

  node_file=$(verified_download $download || verified_download $alt_download) || {
    rm -rf "$version_dir"
    exit 1
  }
  # Download source and compile it
  tar zxf "$node_file" -C /tmp && \
    cd $work_dir && \
    ($PYTHON ./configure --prefix="$version_dir" && make && make install) 2>&1 > /tmp/nodenv-install-$version.log && \
    rm "$node_file" && \
    rm -rf $work_dir || \
    {
      cd $OLDPWD
      rm -rf "$version_dir" "$node_file" $work_dir

      echo "nodenv: installation of $version from source failed" >&2
      exit 1
    }
else
  # Determine url to download from
  platform="$(uname -s | tr '[:upper:]' '[:lower:]')"

  if [ "$(uname -m)" = "x86_64" ]; then
    arch="x64"
  else
    arch="$(uname -p)"
  fi

  # URL to download from
  if [[ $1 == iojs-* ]];then
    ioversion=${1##*-}
    download="https://iojs.org/dist/${ioversion}/iojs-${ioversion}-${platform}-${arch}.tar.gz"
  else
    download="https://nodejs.org/dist/${version}/node-${version}-${platform}-${arch}.tar.gz"
  fi

  # Can't get too clever here
  set +e

  # Download binary tarball and install
  node_file=$(verified_download $download) || {
    rm -rf "$version_dir"
    exit 1
  }
  tar zxf "$node_file" --strip-components 1 && \
    rm -f "$node_file" || \
    {
      cd $OLDPWD
      rmdir "$version_dir"

      echo "nodenv: unable to install NodeJS \`${version}' from binary, download not available"
      exit 1
    }
fi

chmod -R 755 $version_dir

echo "Installed ${version}"
cd $OLDPWD
