#!/usr/bin/env bash

# nodenv version
version="0.3.2"

# Bomb out if we hit an error, ever
set -e
export -n CDPATH

# Verbose output in debug mode
[ -n "$NODENV_DEBUG" ] && {
  set -x
}

# Helper functions
resolve_link() {
  $(type -p greadlink readlink | head -1) "$1"
}

abs_dirname() {
  local cwd="$(pwd)"
  local path="$1"

  while [ -n "$path" ]; do
    cd "${path%/*}"
    local name="${path##*/}"
    path="$(resolve_link "$name" || true)"
  done

  pwd
  cd "$cwd"
}

# Set up NODENV_ROOT, location where everything lives

if [ -z "${NODENV_ROOT}" ]; then
  NODENV_ROOT="${HOME}/.nodenv"
else
  NODENV_ROOT="${NODENV_ROOT%/}"
fi

export NODENV_ROOT

# Jump into the NODENV_DIR
if [ -z "${NODENV_DIR}" ]; then
  NODENV_DIR="$(pwd)"
else
  cd "${NODENV_DIR}" 2>/dev/null || {
    echo "nodenv: cannot change working directory to \`$NODENV_DIR'"
    exit 1
  } >&2

  NODENV_DIR="$(pwd)"

  cd "$OLDPWD"
fi

export NODENV_DIR

# Pop the first argument, our subcommand
command="$1"

# Make sure we can find out utilities on PATH
bin_path="$(abs_dirname "$0")"
export PATH="${bin_path}":$PATH

case "$command" in
  "" | "-h" | "--help" )
    exec nodenv-help
    ;;

  "-v" | "--version" )
    echo "nodenv ${version}"
    exit
    ;;

  *)
    command_path="${bin_path}/nodenv-${command}"

    [ -x "${command_path}" ] || {
      echo "nodenv: no such command \`$command'" >&2
      exit 1
    }

    shift 1
    exec "$command_path" "$@"
    ;;
esac
