#!/usr/bin/env bash
# Summary: Show the current NodeJS version.

# Bomb out if we hit an error, ever
set -e

# Verbose output in debug mode
[ -n "$NODENV_DEBUG" ] && {
  set -x
}

if [ -z "${NODENV_VERSION}" ]; then
  export NODENV_VERSION_FILE="$(nodenv-version-file)"
  export NODENV_VERSION="$(nodenv-version-file-read "$NODENV_VERSION_FILE" || true)"
fi

version_exists() {
  local version="$1"
  [ -n "${version}" ] && \
    [ -d "${NODENV_ROOT}/versions/${version}" ]
}

no_versions() {
  [ -z "$(nodenv-versions)" ]
}

if [ -z "$NODENV_VERSION" ]; then
  echo "nodenv: couldn't find any version specified for use" >&2
  exit 1
elif version_exists "$NODENV_VERSION"; then
  echo "$NODENV_VERSION"
elif no_versions; then
  echo "nodenv: no versions of NodeJS are currently installed" >&2
  exit 1
else
  echo "nodenv: version \`$NODENV_VERSION' is not installed" >&2
  exit 1
fi
