#!/usr/bin/env bash
# Summary: Configure the shell environment for nodenv
# Usage: eval "$(nodenv init - [<shell>])"

# Bomb out if we hit an error, ever
set -e

# Verbose output in debug mode
[ -n "$NODENV_DEBUG" ] && {
  set -x
}

# Figure out what we're gonna print
print=""
for args in "$@"; do
  if [ "$args" = "-" ]; then
    print=1
    shift
  fi
done

# Check for a shell
shell="$1"
if [ -z "$shell" ]; then
  shell="$(basename "$SHELL")"
fi

# Helpers to get full path
resolve_link() {
  $(type -p greadlink readlink | head -1) $1
}

abs_dirname() {
  local cwd="$(pwd)"
  local path="$1"

  while [ -n "$path" ]; do
    cd "${path%/*}"
    local name="${path##*/}"
    path="$(resolve_link "$name" || true)"
  done

  pwd
  cd "$cwd"
}

is_fish() {
  [ "$shell" = "fish" ]
}

# Set the root of our nodenv install
root="$(abs_dirname "$0")/.."

if [ -z "$print" ]; then
  case "$shell" in
  bash )
    profile='~/.bash_profile'
    ;;
  zsh )
    profile='~/.zshrc'
    ;;
  ksh )
    profile='~/.profile'
    ;;
  fish )
    profile='~/.config/fish/fish.config'
    ;;
  * )
    profile='your profile'
    ;;
  esac

  { echo "# Load nodenv automatically by adding"
    echo "# the following to ${profile}:"
    echo
    is_fish && echo '. (nodenv init - | psub)' || \
      echo 'eval "$(nodenv init -)"'
    echo
  } >&2

  exit 1
fi

mkdir -p "${NODENV_ROOT}/"{shims,versions}

is_fish && {
  echo 'set -x PATH "'${NODENV_ROOT}'/shims" $PATH'
  echo 'nodenv rehash ^/dev/null'
} || {
  echo 'export PATH="'${NODENV_ROOT}'/shims:${PATH}"'
  echo 'nodenv rehash 2>/dev/null'  
}