#!/usr/bin/env bash
#
# Summary: Execute a command from a particular NodeJS version.
#
# Usage: nodenv exec <command> [<args>]
#
# Puts the current NodeJS version onto PATH and runs the specified command.

# Bomb out if we hit an error, ever
set -e

# Verbose output in debug mode
[ -n "$NODENV_DEBUG" ] && {
  set -x
}

# Set the current NodeJS version
if [ -z "$NODENV_VERSION" ]; then
  NODENV_VERSION="$(nodenv version)"

  # Couldn't infer from a file either
  if [ -z "$NODENV_VERSION" ]; then
    echo "nodenv: no \`NODENV_VERSION' configured" >&2
    exit 1
  fi
fi

# if the specified NodeJS version lacks this bin, bail
if [ ! -x "$NODENV_ROOT/versions/$NODENV_VERSION/bin/$1" ]; then
  echo "nodenv: \`$1' does not exist for $NODENV_VERSION" >&2

  for version in "$(nodenv versions)"; do
    if [ -x "$NODENV_ROOT/versions/$version/bin/$1" ]; then
      echo "  $version" >&2
    fi
  done

  exit 1
fi

export NODENV_VERSION

# Put our bindir onto PATH
bindir="$NODENV_ROOT/versions/$NODENV_VERSION/bin"

export PATH="$bindir:$PATH"

exec "$@"
