#!/usr/bin/env bash
#
# Summary: Persist the preferred NodeJS version in the cwd.
#
# Usage: nodenv local <version>
#        nodenv local --unset|-u

# Bomb out if we hit an error, ever
set -e

# Verbose output in debug mode
[ -n "$NODENV_DEBUG" ] && {
  set -x
}

# Set the version
version="$1"

case "$version" in
  "")
    echo "nodenv: a version or --unset is required" >&2
    exit 1
    ;;

  "-u" | "--unset")
    if [ -f "$(pwd)/.node-version" ]; then
      rm "$(pwd)/.node-version"
      echo "Unset local .node-version file"
    elif [ -f "$(pwd)/.nvm-version" ]; then
      rm "$(pwd)/.nvm-version"
      echo "Unset local .nvm-version file"
    else
      echo "nodenv: no local version to unset" >&2
      exit 1
    fi
    ;;

  *)
    echo "$version" > "$(pwd)/.node-version"
    echo "Created $(pwd)/.node-version with $version"
    ;;
esac
